name: empty
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  web_socket_channel: ^3.0.1
  logging: ^1.2.0
  crypto: ^3.0.5
  tuple: ^2.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
